version: '2.1'
services:
  db:
    image: postgres
  web:
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/misgastos
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
